### PR TITLE
fix: Make refreshing channel compatible with BigtableDataClientFactory

### LINKED ISSUE #458: ChannelRefreshing feature is incompatible with BigtableDataClientFactory
Repro:
```java
    BigtableDataSettings settings = BigtableDataSettings.newBuilder()
        .setProjectId(PROJECT_ID)
        .setInstanceId(INSTANCE_ID)
        .setRefreshingChannel(true)
        .build();

    BigtableDataClientFactory f = BigtableDataClientFactory
        .create(settings);

    f.createDefault();
```

```
Exception in thread "main" java.lang.IllegalArgumentException: refreshingChannel only works with InstantiatingGrpcChannelProviders
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:142)
	at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStubSettings$Builder.build(EnhancedBigtableStubSettings.java:791)
	at com.google.cloud.bigtable.data.v2.BigtableDataSettings.<init>(BigtableDataSettings.java:71)
	at com.google.cloud.bigtable.data.v2.BigtableDataSettings.<init>(BigtableDataSettings.java:63)
	at com.google.cloud.bigtable.data.v2.BigtableDataSettings$Builder.build(BigtableDataSettings.java:363)
	at com.google.cloud.bigtable.data.v2.BigtableDataClientFactory.createDefault(BigtableDataClientFactory.java:115)
```

### PR DESCRIPTION
**Pull request by mutianf**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #458  ☕️

### CODE REVIEW

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java [hunk 1]
```diff
@@ -60,16 +76,35 @@
...
-    serviceHelper = new FakeServiceHelper(service);
-    serviceHelper.start();
+    try (ServerSocket ss = new ServerSocket(0)) {
+      port = ss.getLocalPort();
+    }
+
+    fakeServer =
+        ServerBuilder.forPort(port)
+            .addService(service)
+            .addTransportFilter(
```
Comment (kolea2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java:94]: can we instead move this logic to `FakeServiceHelper`?

Comment (mutianf) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java]: 👍 Moved to `FakeServiceHelper`.

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java [hunk 2]
```diff
@@ -189,8 +189,9 @@ public BigtableDataClient createForInstance(
   }
 
   // Update stub settings to use shared resources in this factory
-  private void patchStubSettings(StubSettings.Builder stubSettings) {
+  private void patchStubSettings(EnhancedBigtableStubSettings.Builder stubSettings) {
     stubSettings
+        .setRefreshingChannel(false)
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java:194]: Please add comment, something along the lines of:

Channel refreshing only needs to be configured on the shared ClientContext, derivative clients don't have the ability to reconfigure the refresh logic

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java [hunk 3]
```diff
@@ -806,6 +807,20 @@ public EnhancedBigtableStubSettings build() {
         Preconditions.checkArgument(
             getTransportChannelProvider() instanceof InstantiatingGrpcChannelProvider,
             "refreshingChannel only works with InstantiatingGrpcChannelProviders");
+        InstantiatingGrpcChannelProvider.Builder channelProviderBuilder =
+            ((InstantiatingGrpcChannelProvider) getTransportChannelProvider()).toBuilder();
+        try {
+          channelProviderBuilder.setChannelPrimer(
+              BigtableChannelPrimer.create(
+                  getCredentialsProvider().getCredentials(),
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java:815]: I think there is a subtle bug here:

If the original CredentialsProvider was a GoogleCredentialsProvider then each time getCredentials is called, it will be a new instance, which means the credentials used for refreshing will diverge from the normal request credentials.

I think you need to wrap reset the credentials to be FixedCredentials here. 

Also please move the getCredentials line into its own try/catch its kinda hard to see which line can throw the IOException

Comment (kolea2) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java:815]: To add here, can we add a test to ensure the credentials are consistent?

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java (hunk 2 above)
Comment (mutianf) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactory.java:196]: Added comments.

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java (hunk 3 above)
Comment (mutianf) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubSettings.java]: Updated BigtableDataClientFactoryTest.testCreateWithRefreshingChannel test to verify that getCredentials is only called once by the credentialProvider we set (similar to test testNewClientsShareTransportChannel.testNewClientsShareTransportChannel). Also added a test in EnhancedBigtableStubSettingsTest to make sure it's returning the same credentials.

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java [hunk 4]
```diff
@@ -60,16 +73,32 @@
...
+        new ServerTransportFilter() {
+          @Override
+          public Attributes transportReady(Attributes transportAttrs) {
+            attributes.add(transportAttrs);
+            return super.transportReady(transportAttrs);
+          }
+
+          @Override
+          public void transportTerminated(Attributes transportAttrs) {
+            attributes.add(transportAttrs);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java:93]: Might be good to split termination attrs from setup attrs

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java [hunk 5]
```diff
@@ -191,8 +220,95 @@ public void testCreateForInstanceWithAppProfileHasCorrectSettings() throws Excep
...
+    InstantiatingGrpcChannelProvider.Builder channelProviderBuilder = channelProvider.toBuilder();
+    channelProviderBuilder.setPoolSize(poolSize);
+    builder.stubSettings().setTransportChannelProvider(channelProviderBuilder.build());
+
+    BigtableDataClientFactory factory = BigtableDataClientFactory.create(builder.build());
+    factory.createDefault();
+    factory.createForAppProfile("other-appprofile");
+    factory.createForInstance("other-project", "other-instance");
+
+    // Make sure that only 1 instance is created by each provider
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/BigtableDataClientFactoryTest.java:250]: Make sure that only 1 instance is created for all clients

**Review by igorbernstein2 — APPROVED** [review]
lgtm
