### PR TITLE
fix: Filters should be serializable

### LINKED ISSUE #385: Filters should be serializable
This would facilitate the ability to write parameterized DoFns for beam

### PR DESCRIPTION
**Pull request by dmitry-fa**
Fixes #385

### CODE REVIEW

File: proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilterOrBuilder.java [hunk 1]
```diff
@@ -18,10 +18,13 @@
 
 package com.google.bigtable.v2;
 
+import java.io.Serializable;
+
 public interface RowFilterOrBuilder
     extends
-    // @@protoc_insertion_point(interface_extends:google.bigtable.v2.RowFilter)
-    com.google.protobuf.MessageOrBuilder {
+        // @@protoc_insertion_point(interface_extends:google.bigtable.v2.RowFilter)
```
Comment (kolea2) [inline proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilterOrBuilder.java:25]: unfortunately anything in the `proto-*` or `grpc-*` modules are auto generated and cannot be modified by hand.

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java [hunk 2]
```diff
@@ -200,6 +200,7 @@ public Filter label(@Nonnull String label) {
   // Implementations of target specific filters.
   /** DSL for adding filters to a chain. */
   public static final class ChainFilter implements Filter {
+    private static final long serialVersionUID = -89237431180618430L;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/Filters.java:203]: Here and everwhere else: The proto builders will need to be marked transient and you will need to implement writeObject/readObject to serialize the built protos:

```
void writeObject(ObjectOutputStream s) {
  s.defaultWriteObject();
  s.writeObject(builder.build());
}
```

File: proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilter.java [hunk 3]
```diff
@@ -18,6 +18,8 @@
 
 package com.google.bigtable.v2;
 
+import java.io.Serializable;
```
[the remark this answers is not in the document]
Comment (dmitry-fa) [reply proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilter.java:21]: Yes, I see. Is there any way to customize the way how this class is generated?

[the remark this answers is not in the document]
Comment (dmitry-fa) [reply proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilter.java:21]: Oh, looks like it's not needed.

File: proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilterOrBuilder.java (hunk 1 above)
Comment (dmitry-fa) [reply proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilterOrBuilder.java]: thanks, the changes are rolled back.

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 4]
```diff
@@ -528,4 +540,44 @@ public void labelTest() {
...
+          trySerialization(m.invoke(FILTERS, params));
+        } catch (Exception e) {
+          fail(name + ": " + e);
+        }
+      }
+    }
+  }
+
+  private void trySerialization(Object obj) throws IOException, ClassNotFoundException {
+    Path serFile = Files.createTempFile("filter", ".ser");
```
[the remark this answers is not in the document]
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java]: done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 5]
```diff
@@ -528,4 +540,44 @@ public void labelTest() {
...
+    // map methodName -> methodArguments (for those methods which require parameters)
+    Map<String, Object[]> parameterMap = new HashMap<>();
+    parameterMap.put("condition", new Object[] {FILTERS.pass()});
+    parameterMap.put("label", new Object[] {"label"});
+    parameterMap.put("fromProto", new Object[] {FILTERS.label("label").toProto()});
+
+    for (Method m : Filters.class.getDeclaredMethods()) {
+      String name = m.getName();
+      if (Modifier.isPublic(m.getModifiers())) {
+        Object[] params = parameterMap.get(name);
```
[the remark this answers is not in the document]
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java]: done with a minor change:
```
if (!public) {continue} 
swtich()...
```
->
```
if (public) {
  swtich()...
} 
```

I don't like using `continue`, but if you insist, I'll update as you suggested.

File: proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilter.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (dmitry-fa) [reply proto-google-cloud-bigtable-v2/src/main/java/com/google/bigtable/v2/RowFilter.java]: changes are rolled back.

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 6]
```diff
@@ -528,4 +538,66 @@ public void labelTest() {
...
+            checkSerialization(name, m.invoke(FILTERS));
+        }
+      }
+    }
+  }
+
+  private void checkSerialization(String name, Object filter) {
+    try {
+      Object deserialized = serializeDeserialize(filter);
+      if (filter instanceof Filters.Filter) {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:579]: why if? when is this false?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 7]
```diff
@@ -528,4 +538,66 @@ public void labelTest() {
...
+        RowFilter protoBefore = ((Filters.Filter) filter).toProto();
+        RowFilter protoAfter = ((Filters.Filter) deserialized).toProto();
+        assertEquals(
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:582]: Please use https://truth.dev/

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 8]
```diff
@@ -528,4 +538,66 @@ public void labelTest() {
...
+            "'" + name + "' filter protoBuf mismatch after deserialization",
+            protoBefore,
+            protoAfter);
+      }
+    } catch (IOException | ClassNotFoundException e) {
+      fail(name + ": " + e);
+    }
+  }
+
+  private Object serializeDeserialize(Object obj) throws IOException, ClassNotFoundException {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:592]: static?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 9]
```diff
@@ -528,4 +538,66 @@ public void labelTest() {
...
+            checkSerialization(name, FILTERS.label("label").toProto());
+            break;
+          default:
+            checkSerialization(name, m.invoke(FILTERS));
+        }
+      }
+    }
+  }
+
+  private void checkSerialization(String name, Object filter) {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:576]: static?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java [hunk 10]
```diff
@@ -528,4 +538,66 @@ public void labelTest() {
...
+      if (filter instanceof Filters.Filter) {
+        RowFilter protoBefore = ((Filters.Filter) filter).toProto();
+        RowFilter protoAfter = ((Filters.Filter) deserialized).toProto();
+        assertEquals(
+            "'" + name + "' filter protoBuf mismatch after deserialization",
+            protoBefore,
+            protoAfter);
+      }
+    } catch (IOException | ClassNotFoundException e) {
+      fail(name + ": " + e);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:588]: why not just bubble the exception up?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 6 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:579]: `Filters.Filter` interface declares `toProto()` which I can call to verify the deserialized object.

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 8 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:592]: yes. 
I'm thinking about moving this method to a utility class because it's very generic and could be used by any tests for serialization. Do you know a better place for it?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 10 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:588]: in case of this exception, one will have a hard time trying to find which filter caused it. `fail(name + ": " + e)` tells the name of filter in trouble.

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 7 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java]: done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 8 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java]: done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 9 above)
Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java]: done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java (hunk 6 above)
Comment (igorbernstein2) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:579]: But when is it false? from what I can tell all methods defined on Filters return a Filter. If I'm missing something and there are methods that dont return a Filter, then we need to have an explicit whitelist. As it stands its very easy for this test to miss testing a method

Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:579]: it's ~50-50:
a filter 'condition' ConditionFilter
a filter 'label' SimpleFilter
a filter 'chain' ChainFilter
a filter 'interleave' InterleaveFilter
a filter 'pass' SimpleFilter
a filter 'block' SimpleFilter
a filter 'sink' SimpleFilter
not a filter 'family' FamilyFilter
not a filter 'fromProto' RowFilter
not a filter 'qualifier' QualifierFilter
not a filter 'limit' LimitFilter
not a filter 'value' ValueFilter
not a filter 'offset' OffsetFilter
not a filter 'key' KeyFilter
not a filter 'timestamp' TimestampFilter

Comment (igorbernstein2) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:579]: So that means the vast majority of the filters arent getting tested, right?

ie we would want to ensure that qualifier().regex() produces a serializable filter. I think we would want to include a switch case for the not filters and do another loop:


switch(name) {
case "qualifier":
  verifyQualifierFilters();
...
}

verifyQualifierFilters(QualifierFilter f) {
  for (Method m : f.class.getDeclaredMethods()) {
    // ...
  }

Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:581]: qualifier().regex()  does not use any object fields it could be made static, so serialization-deserialization doesn't affect it.

I suggested a better approach to verify non-filter instances, please check.

Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:581]: @igorbernstein2 please take a look at new tests

Comment (dmitry-fa) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/models/FiltersTest.java:581]: @igorbernstein2 gentle ping, in case you missed this update of the tests. I did as you asked for.

**Review by igorbernstein2 — APPROVED** [review]
lgtm
