### PR TITLE
fix: RowCells are not actually serializeable

### LINKED ISSUE #384: RowCells are not actually serializeable
RowCells might contain UnmodifiableLazyStringList for values, which are not actually serializable. 
We need to add custom hooks to RowCell to fix serialization.

The primary issue is that labels are a UnmodifiableLazyStringList, which is not serializeable

### PR DESCRIPTION
**Pull request by dmitry-fa**
Fixes #384

### CODE REVIEW

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java [hunk 1]
```diff
@@ -62,7 +63,8 @@ public static RowCell create(
       long timestamp,
       @Nonnull List<String> labels,
       @Nonnull ByteString value) {
-    return new AutoValue_RowCell(family, qualifier, timestamp, value, labels);
+    // Ensure that the list is serializable and optimize for the common case
+    return new AutoValue_RowCell(family, qualifier, timestamp, value, ImmutableList.copyOf(labels));
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java:67]: This doesnt optimize for the common case. The common case is empty labels. This is currently creating an extra allocation. Optimization would be:

labels = labels.isEmpty()? ImmutableList.of() : ImmutableList.copyOf(labels);

Comment (dmitry-fa) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/models/RowCell.java:72]: Yes, indeed. I assumed `ImmutableList.of()` accepts var args, but it is not.
Ternary Operator does not work here(the compiler is not happy), so I have to use `if`.

Please take a look.

**Review by igorbernstein2 — APPROVED** [review]
lgtm.
Thanks for fixing this
