### PR TITLE
fix: update the accounting of partial batch mutations

### LINKED ISSUE #1494: Batcher error accounting is incorrect when the RPC fails
MutateRowsAttemptCallable when it encounters either RPC or entry errors will resolve its future with a synthetic MutateRowsException. The synthetic error has an INTERNAL status but it marked as retriable. This is done so that the parent RetryableFuture retries the remaining entries. However, once there are no more retriable entries, the MutateRowsException will bubble up to BatcherImpl.Batch#onBatchFailure, which will feed into BatcherStats, which will record the RPC error as INTERNAL

### PR DESCRIPTION
**Pull request by ron-gal**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)
- [x] Rollback plan is reviewed and LGTMed
- [x] All new data plane features have a completed end to end testing plan

Fixes #1494 ☕️

If you write sample code, please follow the [samples format](
https://github.com/GoogleCloudPlatform/java-docs-samples/blob/main/SAMPLE_FORMAT.md).

### CODE REVIEW

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java [hunk 1]
```diff
@@ -672,20 +674,16 @@ public Map<String, String> extract(MutateRowRequest mutateRowRequest) {
...
-                      @Override
-                      public Map<String, String> extract(MutateRowsRequest mutateRowsRequest) {
-                        return ImmutableMap.of(
+                    mutateRowsRequest ->
+                        ImmutableMap.of(
                             "table_name", mutateRowsRequest.getTableName(),
-                            "app_profile_id", mutateRowsRequest.getAppProfileId());
-                      }
-                    })
+                            "app_profile_id", mutateRowsRequest.getAppProfileId()))
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java:686]: please revert extraneous changes

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java [hunk 2]
```diff
@@ -706,22 +704,23 @@ public Map<String, String> extract(MutateRowsRequest mutateRowsRequest) {
...
 
-    BasicResultRetryAlgorithm<Void> resultRetryAlgorithm;
+    BasicResultRetryAlgorithm<MutateRowsAttemptResult> resultRetryAlgorithm;
     if (settings.getEnableRetryInfo()) {
       resultRetryAlgorithm = new RetryInfoRetryAlgorithm<>();
     } else {
       resultRetryAlgorithm = new ApiResultRetryAlgorithm<>();
     }
+    MutateRowsErrorRetryAlgorithm mutateRowsErrorRetryAlgorithm =
+        new MutateRowsErrorRetryAlgorithm(resultRetryAlgorithm);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java:714]: Please name this a bit more specific: MutateRowsPartialErrorRetryAlgorithm

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java [hunk 3]
```diff
@@ -745,16 +744,17 @@ public Map<String, String> extract(MutateRowsRequest mutateRowsRequest) {
    *   <li>Add tracing & metrics.
    * </ul>
    */
-  private UnaryCallable<BulkMutation, Void> createBulkMutateRowsCallable() {
-    UnaryCallable<MutateRowsRequest, Void> baseCallable = createMutateRowsBaseCallable();
+  private UnaryCallable<BulkMutation, MutateRowsAttemptResult> createBulkMutateRowsCallable() {
+    UnaryCallable<MutateRowsRequest, MutateRowsAttemptResult> baseCallable =
+        createMutateRowsBaseCallable();
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java:749]: Can you concatenate createBulkMutateRowsCallable with createMutateRowsBaseCallable? And call it createMutateRowsBaseCallable? nothing seems to use createMutateRowsBaseCallable

Also please add javadoc explaining that the BaseCallable uses an internal result type

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java [hunk 4]
```diff
@@ -1171,11 +1171,13 @@ public UnaryCallable<RowMutation, Void> mutateRowCallable() {
...
 
   /**
-   * Returns the callable chain created in {@link #createBulkMutateRowsCallable()} ()} during stub
+   * Returns the callable chain created in {@link #createBulkMutateRowsCallable()} during stub
    * construction.
    */
   public UnaryCallable<BulkMutation, Void> bulkMutateRowsCallable() {
-    return bulkMutateRowsCallable;
+    UnaryCallable<BulkMutation, Void> errorsConverter =
+        new MutateRowsErrorConverterUnaryCallable(bulkMutateRowsCallable);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java:1179]: do we need to instantiate the MutateRowsErrorConverterUnaryCallable every time?

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/MutateRowsErrorConverterUnaryCallable.java [hunk 5]
```diff
@@ -0,0 +1,49 @@
...
+import com.google.api.core.ApiFuture;
+import com.google.api.core.ApiFutures;
+import com.google.api.gax.rpc.ApiCallContext;
+import com.google.api.gax.rpc.UnaryCallable;
+import com.google.cloud.bigtable.data.v2.models.BulkMutation;
+import com.google.cloud.bigtable.data.v2.models.MutateRowsException;
+import com.google.cloud.bigtable.data.v2.stub.mutaterows.MutateRowsAttemptResult;
+import com.google.common.util.concurrent.MoreExecutors;
+
+public class MutateRowsErrorConverterUnaryCallable extends UnaryCallable<BulkMutation, Void> {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/MutateRowsErrorConverterUnaryCallable.java:27]: Please mark this class as `@InternalApi` and add javadoc explaining what it does. Something along the lines of "This converts partial batch failures into an exception. This is necessary to make sure that the caller properly handles issues and avoid possible data loss

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java [hunk 6]
```diff
@@ -116,25 +116,16 @@ public Object getTransportCode() {
...
-  private final ApiFunction<List<MutateRowsResponse>, Void> attemptSuccessfulCallback =
-      new ApiFunction<List<MutateRowsResponse>, Void>() {
-        @Override
-        public Void apply(List<MutateRowsResponse> responses) {
-          handleAttemptSuccess(responses);
-          return null;
-        }
-      };
+  private final ApiFunction<List<MutateRowsResponse>, MutateRowsAttemptResult>
+      attemptSuccessfulCallback = responses -> handleAttemptSuccess(responses);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java:123]: Please revert extra formatting changes...it makes it hard to see the real change

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java [hunk 7]
```diff
@@ -116,25 +116,16 @@ public Object getTransportCode() {
...
   private final ApiFunction<Throwable, List<MutateRowsResponse>> attemptFailedCallback =
-      new ApiFunction<Throwable, List<MutateRowsResponse>>() {
-        @Override
-        public List<MutateRowsResponse> apply(Throwable throwable) {
-          handleAttemptError(throwable);
-          return null;
-        }
+      throwable -> {
+        handleAttemptError(throwable);
+        return null;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java:128]: Please revert extra formatting changes...it makes it hard to see the real change

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java [hunk 8]
```diff
@@ -148,12 +139,12 @@ public List<MutateRowsResponse> apply(Throwable throwable) {
     this.callContext = Preconditions.checkNotNull(callContext, "callContext");
     this.retryableCodes = Preconditions.checkNotNull(retryableCodes, "retryableCodes");
     this.retryAlgorithm = retryAlgorithm;
-    this.attemptSettings = retryAlgorithm.createFirstAttempt();
+    this.attemptSettings = retryAlgorithm.createFirstAttempt(null);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java:142]: I'm a bit confused why the arg was introduced here

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+package com.google.cloud.bigtable.data.v2.stub.mutaterows;
+
+import com.google.cloud.bigtable.data.v2.models.MutateRowsException.FailedMutation;
+import java.util.ArrayList;
+import java.util.List;
+
+public class MutateRowsAttemptResult {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java:22]: Please mark this as `@InternalApi`  and add javadoc explaining the purpose of this class

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+
+  public boolean isRetryable;
+  public List<FailedMutation> failedMutations;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java:25]: these should be final

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java (hunk 9 above)
Comment (igorbernstein2) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java:22]: Also I would highly recommend to use `AutoValue` for value classes

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java [hunk 11]
```diff
@@ -46,7 +46,11 @@ public BatchingRequestBuilder<RowMutationEntry, BulkMutation> newRequestBuilder(
   }
 
   @Override
-  public void splitResponse(Void response, List<BatchEntry<RowMutationEntry, Void>> entries) {
+  public void splitResponse(
+      MutateRowsAttemptResult response, List<BatchEntry<RowMutationEntry, Void>> entries) {
+    for (FailedMutation mutation : response.failedMutations) {
+      entries.get(mutation.getIndex()).getResultFuture().setException(mutation.getError());
+    }
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java:53]: please add a comment explaining the logic here....its not obvious that ordering matters here and that you are depending on the future being able to be rsesolved once

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java [hunk 12]
```diff
@@ -0,0 +1,78 @@
...
+
+import com.google.api.core.InternalApi;
+import com.google.api.gax.retrying.BasicResultRetryAlgorithm;
+import com.google.api.gax.retrying.RetryingContext;
+import com.google.api.gax.retrying.TimedAttemptSettings;
+import com.google.cloud.bigtable.data.v2.stub.mutaterows.MutateRowsAttemptResult;
+import org.checkerframework.checker.nullness.qual.Nullable;
+
+@InternalApi
+public class MutateRowsErrorRetryAlgorithm
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java:26]: This needs javadoc
Also why do you inherit from BasicResultRetryAlgorithm? I dont think you need that impl and just use the underlying interface

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java [hunk 13]
```diff
@@ -0,0 +1,78 @@
...
+    extends BasicResultRetryAlgorithm<MutateRowsAttemptResult> {
+  BasicResultRetryAlgorithm<MutateRowsAttemptResult> retryAlgorithm;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java:28]: private & final

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java [hunk 14]
```diff
@@ -0,0 +1,78 @@
...
+
+  @Override
+  public TimedAttemptSettings createNextAttempt(
+      RetryingContext context,
+      Throwable previousThrowable,
+      MutateRowsAttemptResult previousResponse,
+      TimedAttemptSettings previousSettings) {
+    return retryAlgorithm.createNextAttempt(
+        context, previousThrowable, previousResponse, previousSettings);
+  }
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java:51]: please move the dumb delegates done as they arent interesting and pull the actual relevant overrides up

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java [hunk 15]
```diff
@@ -0,0 +1,78 @@
...
+  @Override
+  public boolean shouldRetry(
+      Throwable previousThrowable, MutateRowsAttemptResult previousResponse) {
+    if (retryAlgorithm.shouldRetry(previousThrowable, previousResponse)) {
+      return true;
+    }
+    if (previousResponse == null) {
+      return false;
+    }
+    return previousResponse.isRetryable;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java:62]: The ordering seems wrong here. Your logic should be something like:
did the last attempt end in a partial failure?
  yes -> then return if any of the entries were retriable
  no- > then use the underlying logic of the delegate

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java [hunk 16]
```diff
@@ -0,0 +1,78 @@
...
+  }
+
+  @Override
+  public boolean shouldRetry(
+      @Nullable RetryingContext context,
+      Throwable previousThrowable,
+      MutateRowsAttemptResult previousResponse) {
+    if (retryAlgorithm.shouldRetry(context, previousThrowable, previousResponse)) {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsErrorRetryAlgorithm.java:70]: same as above

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java [hunk 17]
```diff
@@ -592,6 +591,73 @@ public void testReadChangeStreamWaitTimeoutIsSet() throws Exception {
...
+  //
+  //   BatchingException batchingException =
+  //       Assert.assertThrows(BatchingException.class, () -> batcher.close());
+  //
+  //   // Overall RPC status was PERMISSION_DENIED, so the error message should be something like
+  //   // Batching finished with 1 batches failed to apply due to: 1 ApiException(1
+  // PERMISSION_DENIED)
+  //   assertThat(batchingException).hasMessageThat().contains("PERMISSION_DENIED");
+  // }
+
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java:660]: ?

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java [hunk 18]
```diff
@@ -474,4 +480,22 @@ public Object answer(InvocationOnMock invocation) {
...
+    }
+
+    @Override
+    public ApiFuture<MutateRowsAttemptResult> futureCall(
+        BulkMutation request, ApiCallContext context) {
+      ApiFuture<Void> future = innerCallable.futureCall(request, context);
+      return ApiFutures.transform(
+          future, result -> new MutateRowsAttemptResult(), MoreExecutors.directExecutor());
+    }
+  }
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java:500]: I dont understand what this is doing

**Review by igorbernstein2 — CHANGES_REQUESTED** [review]

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java (hunk 11 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptor.java:57]: Done

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java (hunk 1 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java]: Done

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java (hunk 7 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java]: Done

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java (hunk 6 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java]: Done

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java (hunk 8 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptCallable.java]: Reverted, as to not mix functional changes with random changes

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsPartialErrorRetryAlgorithm.java [hunk 19]
```diff
@@ -0,0 +1,82 @@
...
+  @Override
+  public boolean shouldRetry(
+      Throwable previousThrowable, MutateRowsAttemptResult previousResponse) {
+    if (previousResponse == null) {
+      return retryAlgorithm.shouldRetry(previousThrowable, null);
+    }
+    if (!previousResponse.failedMutations.isEmpty()) {
+      return previousResponse.isRetryable;
+    }
+    return retryAlgorithm.shouldRetry(previousThrowable, previousResponse);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsPartialErrorRetryAlgorithm.java:48]: I dont quite understand the logic here. Why are you calling the underlying retryAlgorithm twice?
I think this would make a lot more sense:

```java
// handle partial retriable failures
if (previousResponse != null && !previousResponse.failedMutations.isEmpty()) {
  return previousResponse.isRetryable; 
}
// business as usual
return retryAlgorithm.shouldRetry(previousThrowable, previousResponse);
```

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsPartialErrorRetryAlgorithm.java [hunk 20]
```diff
@@ -0,0 +1,82 @@
...
+      @Nullable RetryingContext context,
+      Throwable previousThrowable,
+      MutateRowsAttemptResult previousResponse) {
+    if (previousResponse == null) {
+      return retryAlgorithm.shouldRetry(context, previousThrowable, null);
+    }
+    if (!previousResponse.failedMutations.isEmpty()) {
+      return previousResponse.isRetryable;
+    }
+    return retryAlgorithm.shouldRetry(context, previousThrowable, previousResponse);
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/gaxx/retrying/MutateRowsPartialErrorRetryAlgorithm.java:62]: same as above

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java [hunk 21]
```diff
@@ -592,6 +594,56 @@ public void testReadChangeStreamWaitTimeoutIsSet() throws Exception {
     }
   }
 
+  @Test
+  public void testBatchMutationsPartialFailure() throws InterruptedException {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java:598]: Its really hard to see what is being tested.  I see the setup for the test and I see code that triggers the mocked behavior  (which oddly comes beforecausing an unnecessary race). But I dont see what anything being inspected nor do I see anything being verified.
In fact this seems to show a bug, as I would expect batcher.close() to throw an exception

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java [hunk 22]
```diff
@@ -592,6 +594,56 @@ public void testReadChangeStreamWaitTimeoutIsSet() throws Exception {
...
+              observer.onCompleted();
+              return null;
+            })
+        .when(Mockito.mock(FakeDataService.class))
+        .mutateRows(Mockito.any(MutateRowsRequest.class), Mockito.any(StreamObserver.class));
+    batcher.close();
+  }
+
+  @Test
+  public void testBatchMutationRPCErrorCode() throws InterruptedException {
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java:630]: Same as above

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java (hunk 18 above)
Comment (igorbernstein2) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/metrics/MetricsTracerTest.java:500]: Please don't do that, instead please make the private callable public and use it.

I can think of 2 ways to make it public:

1. mark the method as package private. Then add a helper class in `src/test/java/com/google/cloud/bigtable/data/v2/stub` that has a public method to extract the callable from a stub ie:
```java
public class StubPrivateAccessor {
  public static UnaryableCallable<...> getMutateRowsBaseCallable(EnhancedBigtableStub s) {
     return s.mutateRowsStub()
  }
}
```

2. add a public getter to the EnhancedStub for the callable and mark it as InternalApi

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java [hunk 23]
```diff
@@ -92,11 +96,54 @@ public void splitResponseTest() {
...
+                        "error message",
+                        null,
+                        GrpcStatusCode.of(io.grpc.Status.Code.INTERNAL),
+                        false))),
+            true),
+        batchResponse);
+    assertThat(batchResponse.get(0).getResultFuture().isDone()).isTrue();
+    assertThat(batchResponse.get(1).getResultFuture().isDone()).isTrue();
+
+    batchResponse.get(1).getResultFuture().get();
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java:134]: Please call this out as a verification of no errors being thrown. 2 options:
1. do it in code
```java
Throwable unexpectedError = null;
try {
  batchResponse.get(1).getResultFuture().get();
  
} catch (Throwable t) {
  unexpectedError = t;
}
assertThat(unexpectedError).isNull();
```
2. Add a comment
```
// verify that ok entry's future does not throw an exception
batchResponse.get(1).getResultFuture().get();
```

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java [hunk 24]
```diff
@@ -92,11 +96,54 @@ public void splitResponseTest() {
...
+
+    Throwable actualError = null;
+    try {
+      batchResponse.get(0).getResultFuture().get();
+    } catch (Throwable t) {
+      actualError = t.getCause();
+    }
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsBatchingDescriptorTest.java:141]: This would be better:
```
Throwable actualError = assertThrows(
  ExecutionException.class,
  () -> batchResponse.get(0).getResultFuture().get()
 ).getCause();
```

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java [hunk 25]
```diff
@@ -0,0 +1,87 @@
...
+import org.junit.runners.JUnit4;
+import org.mockito.ArgumentCaptor;
+import org.mockito.Mockito;
+
+@RunWith(JUnit4.class)
+public class MutateRowsErrorConverterUnaryCallableTest {
+
+  private static final RequestContext REQUEST_CONTEXT =
+      RequestContext.create("fake-project", "fake-instance", "fake-profile");
+  private UnaryCallable<BulkMutation, MutateRowsAttemptResult> innerCallable;
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java:43]: A better approach would be:

1. add mockito junit rule:
```@Rule public final MockitoRule mockitoRule = MockitoJUnit.rule()```
2. Annotate your mockito instance variables:
```
@Mock
private UnaryCallable<BulkMutation, MutateRowsAttemptResult> innerCallable;
@Captor 
private ArgumentCaptor<BulkMutation> innerMutation;
```

3. remove the Mockito.mock & ArgumentCaptor from setup

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java [hunk 26]
```diff
@@ -0,0 +1,87 @@
...
+        .thenReturn(innerResult);
+  }
+
+  @Test
+  public void testSuccess() {
+    MutateRowsErrorConverterUnaryCallable callable =
+        new MutateRowsErrorConverterUnaryCallable(innerCallable);
+
+    innerResult.set(new MutateRowsAttemptResult());
+    callable.call(BulkMutation.create("fake-table"));
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java:63]: its unclear whats being tested here

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java [hunk 27]
```diff
@@ -0,0 +1,87 @@
...
+            true));
+
+    MutateRowsException exception =
+        Assert.assertThrows(
+            MutateRowsException.class, () -> callable.call(BulkMutation.create("fake-table")));
+
+    assertThat(exception).isInstanceOf(MutateRowsException.class);
+    assertThat((exception).isRetryable()).isTrue();
+  }
+}
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java:87]: What about a test for full RPC failure?

**Review by igorbernstein2 — CHANGES_REQUESTED** [review]
Added a bunch of comments. But more broadly the main piece thats missing is tests for the 2 root problems:
1. that the error messages for partial failures does not include anything about INTERNAL errors
2. that the metrics for partial failures count as OK

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java (hunk 25 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java]: Done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java (hunk 26 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java]: Fixed

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java (hunk 27 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsErrorConverterUnaryCallableTest.java:109]: Done

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java (hunk 9 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java]: Done

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java (hunk 21 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java]: Fixed

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java (hunk 22 above)
Comment (ron-gal) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStubTest.java]: Fixed

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java [hunk 28]
```diff
@@ -0,0 +1,42 @@
...
+package com.google.cloud.bigtable.data.v2.stub.mutaterows;
+
+import com.google.api.core.InternalApi;
+import com.google.cloud.bigtable.data.v2.models.MutateRowsException.FailedMutation;
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * This class represents the result of a MutateRows attempt. It contains the list of failed
+ * mutations, along with an indicator whether these errors are retryable.
```
[the remark this answers is not in the document]
Comment (igorbernstein2) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java:27]: ping

**Review by igorbernstein2 — APPROVED** [review]

**Comment by igorbernstein2** [comment]
Can you add an exception to the [clirr config](https://github.com/googleapis/java-bigtable/blob/main/google-cloud-bigtable/clirr-ignored-differences.xml) for
7005: com.google.cloud.bigtable.data.v2.stub.mutaterows.MutateRowsBatchingDescriptor: Parameter 1 of 'public void splitResponse(java.lang.Void, java.util.List)' has changed its type to com.google.cloud.bigtable.data.v2.stub.mutaterows.MutateRowsAttemptResult

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (ron-gal) [reply google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/mutaterows/MutateRowsAttemptResult.java]: Done
