### PR TITLE
fix: Retry "received rst stream"

### LINKED ISSUE #106: Bigtable: INTERNAL: HTTP/2 error code: INTERNAL_ERROR Received Rst Stream as a retryable status code
Long lived connections are sometimes disconnected via a RST frame. These should be handled similar to UNAVAILABLE. Also need to make sure that GOAWAYs are handled similar.

This is the same issue as https://github.com/googleapis/cloud-bigtable-client/issues/2177

### PR DESCRIPTION
**Pull request by mutianf**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/java-bigtable/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #106  ☕️

### CODE REVIEW

File: google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java [hunk 1]
```diff
@@ -365,10 +366,14 @@ public EnhancedBigtableStub(EnhancedBigtableStubSettings settings, ClientContext
         new HeaderTracerStreamingCallable<>(
             watched, settings.getHeaderTracer(), getSpanName("ReadRows").toString());
 
+    // Check for "received rst stream" exceptions and convert them to retryable ApiExceptions
+    ServerStreamingCallable<ReadRowsRequest, RowT> convertException =
+        new ReadRowsConvertExceptionCallable<>(withHeaderTracer);
+
```
Comment (igorbernstein2) [inline google-cloud-bigtable/src/main/java/com/google/cloud/bigtable/data/v2/stub/EnhancedBigtableStub.java:372]: I think this should be a lot deeper in the call chain, it modifies the behavior of the exception callable thats created in the raw callable.

**Comment by mutianf** [comment]
@igorbernstein2 Updated the code and comment, ready for another review :)

**Review by igorbernstein2 — APPROVED** [review]
looks great, thanks for fixing this!
