### PR TITLE
fix: parallel execution and verbose grpc logs

### LINKED ISSUE #692: during tests verbose grpc logs are not split by  test

### PR DESCRIPTION
**Pull request by igorbernstein2**
Mucking around with java util logging fails when tests are executed in parallel. 
So make the 2 features exclusive: by default tests are executed in parallel, if verbose logs are needed 
they can be activated by a profile that will disable parallel execution.

Also switch parallel tests to run in threads instead of processes 
and enable parallel execution for unit tests

Fixes #692

### CODE REVIEW

File: google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java [hunk 1]
```diff
@@ -122,9 +125,14 @@ protected void before(Description description) throws Throwable {
   }
 
   private void configureLogging(Description description) throws IOException {
-    if (Strings.isNullOrEmpty(BIGTABLE_GRPC_LOG_DIR)) {
+    if (!BIGTABLE_ENABLE_VERBOSE_GRPC_LOGS) {
       return;
     }
+    Preconditions.checkState(
```
Comment (kolea2) [inline google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java:131]: should we be setting this in the kokoro configs?

Comment (igorbernstein2) [reply google-cloud-bigtable/src/test/java/com/google/cloud/bigtable/test_helpers/env/TestEnvRule.java:131]: Yes, it will be set in the kokoro directpath tests via the `enable-verbose-grpc-logs` profile

**Review by kolea2 — APPROVED** [review]
